### ISSUE TITLE
Error Call to a member function get() on null

### ISSUE THREAD

**Issue by mbennett417** [nikosdion/plg_captcha_google#1]
I followed the steps outlined by Tim at Cybersalt on his YT video. This is on my system as a test before I try to deploy to client systems. My system is using PHP 8.1 but I had to upgrade to Joomla 5.2 first after updating all extensions. There were no errors.

After I installed 5.2 I installed this plugin and on the Contacts page where the reCaptcha is shown I get an error screen and the message "0 - Call to a member function get() on null". I went over the steps carefully again and didn't fix it. I turned on logging and debug and get the attached screen.

I have disabled the Google plugin, and I already had the V3 keys.  I did not uninstall the Google plugin.
![Screenshot - 10_23_2024 , 3_02_14 PM](https://github.com/user-attachments/assets/9a8066d1-b977-4531-ade4-d1581cb8e8d5)

Any advice short of moving to an alternate Captcha method?

**Comment by nikosdion** [comment]
Look at your screenshot. You are still using Joomla's now-defunct plugin, **NOT** the plugin from this repository. 

Joomla's plugin: `plugins/captcha/recaptcha_invisible`.

This plugin: `plugins/captcha/google`.

I knew people would mess it up like that, which is why I have the instruction

> Then, go to System, Manage, Plugins and disable Joomla's now-defunct “CAPTCHA - Invisible reCAPTCHA” plugin.

in the [README](https://github.com/nikosdion/plg_captcha_google?tab=readme-ov-file#usage).

**Comment by mbennett417** [comment]
It was disabled and still is.  I guarantee it is disabled. BUT!  It was installed and enabled in version 5.1.  After I installed your plugin it was disabled, which probably happened when version 5.2 was installed.  I'll uninstall it entirely and see what happens.

**Comment by mbennett417** [comment]
Disabling isn't enough, the old plugin must be uninstalled if this error is seen. That did fix the problem. Disabling might not be enough in all cases. NOW the issue is closed, and thank you for your help.

**Comment by mbennett417** [comment]
I think this is where I tripped: "If you have any extensions which were using Joomla's now-defunct plugin explicitly configure in them, remember to edit their options and choose the “CAPTCHA - Google Invisible reCAPTCHA” plugin instead."

I finally dug around and found that I needed to change Components | Categories | Options on the Form tab to update to the new plugin. I think if I had done that I wouldn't have needed to completely uninstall the old plugin.

**Comment by nikosdion** [comment]
And now you understand why I have the uninstall instruction :)

Yes, technically, you don't _need_ to uninstall Joomla's now-defunct plugin. You should do it anyway since it's a broken plugin which won't receive any updates, but that's another thing altogether.

The real reason I tell you to uninstall it is that I know you will very likely have _at least_ one extension using the old plugin explicitly, you will not remember it (as you probably set it up years ago!), and you will see an error thinking it comes from my new plugin. Uninstalling the old plugin will not result in this potentially misleading error message.

**Comment by nikosdion** [comment]
To further clarify, I added this instruction because I also had such an extension on one of my sites, and had indeed forgotten I had selected a specific CAPTCHA plugin. I ran into the same error you did. I immediately realised what the problem is, so I added the instruction to uninstall the old plugin to protect you from a problem I was sure was going to happen ;)

**Comment by mbennett417** [comment]
I'll reiterate it, make sure you uninstall the old plugin first, don't rely on disabling it. Thank you so much for developing and providing this plugin.

**Comment by nikosdion** [comment]
You're welcome! I am happy I could help other people :)
